"""
# 389
Easy
Find the Difference

https://leetcode.com/problems/find-the-difference/

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""


def find_the_difference(s: str, t: str) -> str:
    hm = {}
    for c in s:
        hm[c] = hm.get(c, 0) + 1

    for x in t:
        if x not in hm or hm[x] == 0:
            return x

        hm[x] -= 1


if __name__ == "__main__":
    assert find_the_difference("abcd", "abcde") == "e"
    assert find_the_difference("", "t") == "t"
